
version: 2


sources:
  - name: dp_data_db 
    description: "ad transactions 所依赖的所有底层数据源"
    schema: dp_data_db
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 240, period: day}
    loaded_at_field: STR_TO_DATE(req_request_time,'%Y-%m-%d %H:%i:%s')
    tables:
      - name: ad_trans_baidu_feb_03071
        columns:
          - name: req_request_id
            description: “各个媒体的请求ID”
            tests:
              - not_null
          - name: req_meidia_source
            description: “请求所属的媒体”
            tests:
              - not_null
  - name: fin_dim
    description: 
    schma: fin_dim
    tables: 
      - name: dim_m_audience_group_rta_group_config_daily_jwm_pdi
